In [10]:
import scipy
from scipy import stats
import numpy as np

In [11]:
# criacao dos dados que vamos utilizar
matrix = np.array([[8,0,3,4,6],[5,6,1,8,9],[8,0,0,5,10]])
novo_user = [8,0,2,3,0]
nao_assistidos = [0,1,0,0,1]
print(matrix)
nome_filmes = ['Round 6', 'A invocacao do mal', '9 Desconhecidos', 'You', 'La casa de papel']

[[ 8  0  3  4  6]
 [ 5  6  1  8  9]
 [ 8  0  0  5 10]]


In [20]:
for i in range(0, 3):
    # vamos pegar os dados desse usuário
    print(matrix[i,:])

[8 0 3 4 6]
[5 6 1 8 9]
[ 8  0  0  5 10]


In [22]:
# criando um vetor com 3 posições e preencher com zero (vamos colocar os valores da similaridade entre o novoUser e cada outro usuário da matriz )
similarity = [0] * 3

# para cada usuario no sitema...
for i in range(0, 3):
    # vamos pegar os dados desse usuário
    temp = matrix[i,:]

    print(i, temp)
    # mas queremos apenas comparar os dados que o novo user assistiu (ou seja... que novouser != 0)
    temp_user = [t for n, t in zip(novo_user, temp) if n != 0]
    temp_user_novo = [n for n in novo_user if n!= 0]

    # para verificar o processo
    print('user: ', i)
    print(temp_user, temp_user_novo)

    # vamnos usar a biblioteca scipy.stats que ja calcula o pearson
    similarity[i] = scipy.stats.pearsonr(temp_user, temp_user_novo)[0] #

print(similarity)

------------------------------------------------------------
0 [8 0 3 4 6]
user:  0
[8, 3, 4] [8, 2, 3]
------------------------------------------------------------
1 [5 6 1 8 9]
user:  1
[5, 1, 8] [8, 2, 3]
------------------------------------------------------------
2 [ 8  0  0  5 10]
user:  2
[8, 0, 5] [8, 2, 3]
[0.9994237971287663, 0.23621543814299698, 0.8723686098443353]


In [28]:
nota_peso = np.zeros((3,5))

for nUser in range(3):
  for nFilme in range(5):
    # print('nota_peso[',nUser, '][',nFilme, '] = , nao_assistidos[',nFilme, '], * ,matrix[',nUser,'][',nFilme, '], * similarity[',nUser,']')
    # print('nota_peso[',nUser, '][',nFilme, '] = ', nao_assistidos[nFilme], ' * ' ,matrix[nUser][nFilme], ' * ', similarity[nUser])
    nota_peso[nUser][nFilme] = nao_assistidos[nFilme] * matrix[nUser][nFilme] * similarity[nUser]

print(nota_peso)

[[0.         0.         0.         0.         5.99654278]
 [0.         1.41729263 0.         0.         2.12593894]
 [0.         0.         0.         0.         8.7236861 ]]


In [5]:
notas_acumuladas = np.sum(nota_peso.T,axis=1)
print(notas_acumuladas)

[ 0.          1.41729263  0.          0.         16.84616782]


In [6]:
temp_peso = nota_peso
temp_peso[nota_peso > 0] = 1
print(temp_peso)

temp_similaridade = np.zeros((3,5))
for nUser in range(3):
  for nFilme in range(5):
    temp_similaridade[nUser][nFilme] = temp_peso[nUser][nFilme] * similarity[nUser]

print(temp_similaridade)

similaridade_acumulada = np.sum(temp_similaridade.T,axis=1)
print(similaridade_acumulada)

[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
[[0.         0.         0.         0.         0.9994238 ]
 [0.         0.23621544 0.         0.         0.23621544]
 [0.         0.         0.         0.         0.87236861]]
[0.         0.23621544 0.         0.         2.10800785]


In [7]:
nota_final =[0] * 5
#agora a normalização para cada filme com nota acumulada, eu normalizo pela soma dos pesos (similaridade)
for nFilme in range(5):
  if(similaridade_acumulada[nFilme] > 0):
    nota_final[nFilme] =  notas_acumuladas[nFilme] / similaridade_acumulada[nFilme]
  else:
    nota_final[nFilme] = 0

print(nota_final)

[0, 6.0, 0, 0, 7.991510972567143]


In [9]:
nAssistidos = sum(nao_assistidos)

notasOrdenadasIndex = sorted(range(len(nota_final)),key=nota_final.__getitem__)[::-1][0:nAssistidos]
print(notasOrdenadasIndex)

for i in notasOrdenadasIndex:
  print(nome_filmes[i], 'nota: ', nota_final[i])

[4, 1]
La casa de papel nota:  7.991510972567143
A invocacao do mal nota:  6.0
